 /*
 * File:   egts_defines.h
 * Author: kamyshev.a
 *
 * Created on 1 August 2018, 14: 18
 */

#define EGTS_MAX_PACK_SIZE 65535
#define EGTS_MAX_FRAME_SIZE 65517
#define EGTS_TERM_IN_BUF_SIZE 1024


 // packet type
#define EGTS_PT_RESPONCE 0
#define EGTS_PT_APPDATA 1
#define EGTS_PT_SIGNED_APPDATA 2

 // service type
#define EGTS_AUTH_SERVICE 1
#define EGTS_TELEDATA_SERVICE 2
#define EGTS_COMMANDS_SERVICE 4
#define EGTS_FIRMWARE_SERVICE 9
#define EGTS_ECALL_SERVICE 10
#define EGTS_INSURANCE_SERVICE 20
#define EGTS_EUROPROTOCOL_SERVICE 22

 // processing result codes
#define EGTS_PC_OK 0
#define EGTS_PC_IN_PROGRESS 1
#define EGTS_PC_UNS_PROTOCOL 128
#define EGTS_PC_DECRYPT_ERROR 129
#define EGTS_PC_INC_HEADERFORM 131
#define EGTS_PC_INC_DATAFORM 132
#define EGTS_PC_HEADERCRC_ERROR 137
#define EGTS_PC_DATACRC_ERROR 138
#define EGTS_PC_INVDATALEN 139

// service statement codes
#define EGTS_SST_IN_SERVICE 0
#define EGTS_SST_OUT_OF_SERVICE 128
#define EGTS_SST_DENIED 129
#define EGTS_SST_NO_CONF 130
#define EGTS_SST_TEMP_UNAVAIL 131

#define EGTS_SR_RECORD_RESPONSE 0

 // EGTS_AUTH_SERVICE subrecord type
#define EGTS_SR_TERM_IDENTITY 1
#define EGTS_SR_VEHICLE_DATA 3
#define EGTS_SR_DISPATCHER_IDENTITY 5
#define EGTS_SR_AUTH_PARAMS 6
#define EGTS_SR_AUTH_INFO 7
#define EGTS_SR_SERVICE_INFO 8
#define EGTS_SR_RESULT_CODE 9
#define EGTS_SR_TERM_IDENTITY2 10

 // EGTS_TELEDATA_SERVICE subrecord type
#define EGTS_SR_EGTSPLUS_DATA 15
#define EGTS_SR_POS_DATA 16
#define EGTS_SR_EXT_POS_DATA 17
#define EGTS_SR_AD_SENSORS_DATA 18
#define EGTS_SR_COUNTERS_DATA 19
#define EGTS_SR_STATE_DATA 20
#define EGTS_SR_LIQUID_LEVEL_SENSOR 27
#define EGTS_SR_PASSENGERS_COUNTERS 28

 // EGTS_COMMANDS_SERVICE subrecord type
#define EGTS_SR_COMMAND_DATA 51

 // EGTS_FIRMWARE_SERVICE subrecord type
#define EGTS_SR_SERVICE_PART_DATA 33
#define EGTS_SR_SERVICE_FULL_DATA 34

 // EGTS_ECALL_SERVICE subrecord type
#define EGTS_SR_ACCEL_DATA 20
#define EGTS_SR_RAW_MSD_DATA 40
#define EGTS_SR_MSD_DATA 50
#define EGTS_SR_TRACK_DATA 62

 // EGTS_INSURANCE_SERVICE subrecord type
#define EGTS_SR_INSURANCE_ACCEL_DATA 65
#define EGTS_SR_INSURANCE_TRACK_DATA 66
#define EGTS_SR_INSURANCE_FAILURE 67
#define EGTS_SR_INSURANCE_ACTION 68

 // EGTS_EUROPROTOCOL_SERVICE subrecord type
#define EGTS_SR_EP_MAIN_DATA 1
#define EGTS_SR_EP_TRACK_DATA 2
#define EGTS_SR_EP_ACCEL_DATA 3
#define EGTS_SR_EP_SIGNATURE 4
#define EGTS_SR_EP_RAW_DATA 5
#define EGTS_SR_EP_COMP_DATA 6
#define EGTS_SR_EP_ACCEL_DATA2 7
#define EGTS_SR_EP_ACCEL_DATA3 8

#define EGTS_TL_RESPONSE_TO 5
#define EGTS_TL_RESEND_ATTEMPTS 3
#define EGTS_TL_RECONNECT_TO 30

#define EGTS_SL_NOT_AUTH_TO 6



